### ISSUE TITLE
Crash with Subaquatic caused by AssetMover?

### ISSUE THREAD

**Issue by NoMoreUsernames999** [CleanroomMC/AssetMover#12]
This crash happens when trying to load Subaquatic 1.0.1, AssetMover (tried with AssetMover 2.2 and 2.5), and Custom Loading Screens 1.5.7 together. Just Loading Screens and AssetMover does not cause the crash.  

https://pastebin.com/fiTF0vJw

**Comment by Rongmario** [comment]
Try updating your Java

**Comment by NoMoreUsernames999** [comment]
Java version is latest available for 1.12 (2860).

**Comment by KorewaLidesu** [comment]
That is forge, not java

**Comment by NoMoreUsernames999** [comment]
Lmao, I need to sleep. I'll try that.

**Comment by NoMoreUsernames999** [comment]
TIL Curseforge still uses a Java version that is literally *years* out of date, and doesn't allow changing it. What the actual f Curseforge. Time to drop this shit for Prism.

**Comment by NoMoreUsernames999** [comment]
Ok so after switching to Prism launcher, I tried using java 8_341 which is what I use for most stuff, and the latest (as far as I could tell) _371. Both have identical crashes to the one linked above... Any other ideas? Is there a specific fork of Java I'm supposed to use?

**Comment by KorewaLidesu** [comment]
Can you send the debug log?

**Comment by NoMoreUsernames999** [comment]
Er... Went to launch the game again to make sure the logs were fresh and... it suddenly works the third time? I guess some caches or something needed to be cleared. Idfk lol. Classic modding moment. Well I guess updating finally fixed it, third times the charm. Thks.

**Comment by juraj-hrivnak** [comment]
This issue is still present. I tried to launch the mod several times, and it still crashed.

Debug log: https://mclo.gs/z8apUji#L17144
Subaquatic: v1.1.0-mc1.12.2
AssetMover: 2.5
Java: 1.8.0_371
