### ISSUE TITLE
[Suggestion] Don't depend on Java versions newer than Mojang's default for 1.12.2?

### ISSUE THREAD

**Issue by xJon** [CleanroomMC/AssetMover#13]
Obviously there are reasons for this current limitation. But the current cost of it mean there's no way this mod can be used in a public modpack in CurseForge or Technic, as it can't be expected of all players to manually update Java and set the new version in a launcher - it's a hassle in CurseForge, and in Technic it can't be done per-modpack so it'd break modpacks that depend on Java >8 (e.g. latest vanilla).

Perhaps a workaround of including the `assetmover` folder in the modpack could work for a mod like Subaquatic, but that beats the entire purpose of AssetMover.

**Comment by BJNick** [comment]
I second this. This is a semi-optional dependency for ExtraSoundsLegacy 1.12.2 and adding this mod crashes the game due to an unexplainable null exception inside AssetMover which is likely due to the Java version (crash report: https://pastebin.com/ZhuYihKv).

**Comment by Rongmario** [comment]
This is fixed in https://github.com/LoliKingdom/LoliASM/commit/d44e45fd386b84c76e29caa78ea6aac7413abbd2, a bug that plagues not only AssetMover but other mods also. I highly recommend using it.
