### ISSUE TITLE
Crash with 2.0

### ISSUE THREAD

**Issue by Sereath** [CleanroomMC/AssetMover#4]
https://mclo.gs/Ei4TNyH

All good with 1.1

**Comment by Desenrrollado** [comment]
Similarly crashing in 2.1. 
https://mclo.gs/IFptxSo

Was definitely patched previously and working fine prior. 

Logs:
[latest.log](https://github.com/CleanroomMC/AssetMover/files/10087440/latest.log)
Crash Report: 
[crash-2022-11-24_14.33.25-client.txt](https://github.com/CleanroomMC/AssetMover/files/10087441/crash-2022-11-24_14.33.25-client.txt)

**Comment by Rongmario** [comment]
Will push a fix in a bit

**Comment by ACGaming** [comment]
Would appreciate it!
