### ISSUE TITLE
possible AssetMoverHelper.getVersionJson crash (v2.1)

### ISSUE THREAD

**Issue by jbredwards** [CleanroomMC/AssetMover#5]
I recently made a new mod using this one as a dependency. I haven't gotten this to happen myself yet, but a few people have been reporting this crash https://mclo.gs/KvnUAQa

**Comment by KorewaLidesu** [comment]
Can you ask those who get crash open this?
https://launchermeta.mojang.com/mc/game/version_manifest.json

**Comment by TheRealZonko** [comment]
I've gotten the same crash in the latest 2 updates of AssetMover as well.
