### ISSUE TITLE
[Crash] Crash during startup on v2.3

### ISSUE THREAD

**Issue by Slayer5934** [CleanroomMC/AssetMover#8]
[crash-2023-02-25_20.23.31-client.txt](https://github.com/CleanroomMC/AssetMover/files/10832726/crash-2023-02-25_20.23.31-client.txt)

**Comment by Rongmario** [comment]
Do you have the full log?

**Comment by Slayer5934** [comment]
[2023-02-25-1.log](https://github.com/CleanroomMC/AssetMover/files/10834124/2023-02-25-1.log)

**Comment by Rongmario** [comment]
Update your [Java 8](https://adoptium.net/temurin/releases/?version=8).
